<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PertanyaanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('pertanyaan')->insert([
            [
                'id' => 1,
                'formulir_id' => 1,
                'nomor' => 1,
                'teks' => 'Pada saat bayi terlentang, apakah masing-masing lengan dan tungkai bergerak dengan mudah? Jawab ‘Tidak’ bila salah satu atau kedua tungkai atau lengan bayi bergerak tak terarah atau tak terkendali.',
                'kategori' => 'Gerak kasar',
                'tipe_jawaban' => 'Ya/Tidak',
                'bobot_nilai' => 1,
                'petunjuk_gambar' => null,
                'created_at' => '2025-09-08 21:53:44',
                'updated_at' => '2025-09-08 21:53:44',
            ],
            [
                'id' => 2,
                'formulir_id' => 1,
                'nomor' => 2,
                'teks' => 'Jangan membuat suara apapun. Pada saat bayi terlentang apakah ia melihat dan menatap wajah Anda?',
                'kategori' => 'Sosialisasi dan kemandirian',
                'tipe_jawaban' => 'Ya/Tidak',
                'bobot_nilai' => 1,
                'petunjuk_gambar' => 'pertanyaan/petunjuk_gambar/1757130078_1.png',
                'created_at' => '2025-09-08 21:53:44',
                'updated_at' => '2025-09-08 21:53:44',
            ],
            [
                'id' => 3,
                'formulir_id' => 1,
                'nomor' => 3,
                'teks' => 'Pada saat Anda mengajak bayi berbicara dan tersenyum, apakah ia tersenyum kembali kepada Anda?',
                'kategori' => 'Sosialisasi dan kemandirian',
                'tipe_jawaban' => 'Ya/Tidak',
                'bobot_nilai' => 1,
                'petunjuk_gambar' => null,
                'created_at' => '2025-09-08 21:53:44',
                'updated_at' => '2025-09-08 21:53:44',
            ],
            [
                'id' => 4,
                'formulir_id' => 1,
                'nomor' => 4,
                'teks' => 'Apakah bayi dapat mengeluarkan suara-suara lain (mengoceh) selain menangis?',
                'kategori' => 'Bicara dan bahasa',
                'tipe_jawaban' => 'Ya/Tidak',
                'bobot_nilai' => 1,
                'petunjuk_gambar' => null,
                'created_at' => '2025-09-08 21:53:44',
                'updated_at' => '2025-09-08 21:53:44',
            ],
            [
                'id' => 5,
                'formulir_id' => 1,
                'nomor' => 5,
                'teks' => 'Apakah bayi suka tertawa keras walau tidak digelitik atau diraba-raba?',
                'kategori' => 'Bicara dan bahasa',
                'tipe_jawaban' => 'Ya/Tidak',
                'bobot_nilai' => 1,
                'petunjuk_gambar' => null,
                'created_at' => '2025-09-08 21:53:44',
                'updated_at' => '2025-09-08 21:53:44',
            ],
            [
                'id' => 6,
                'formulir_id' => 1,
                'nomor' => 6,
                'teks' => 'Ambil gulungan wool merah, lalu letakkan di atas wajah di depan mata bayi. Gerakkan wool dari samping kiri ke kanan kepala atau sebaliknya. Apakah ia dapat mengikuti gerakan Anda dengan menggerakkan kepalanya dari kanan atau kiri ke tengah?',
                'kategori' => 'Gerak halus',
                'tipe_jawaban' => 'Ya/Tidak',
                'bobot_nilai' => 1,
                'petunjuk_gambar' => 'pertanyaan/petunjuk_gambar/1757393624_5.png',
                'created_at' => '2025-09-08 21:53:44',
                'updated_at' => '2025-09-08 21:53:44',
            ],
            [
                'id' => 7,
                'formulir_id' => 1,
                'nomor' => 7,
                'teks' => 'Ambil gulungan wool merah, lalu letakkan di atas wajah di depan mata bayi. Gerakkan wool dari samping kiri ke kanan kepala atau sebaliknya. Apakah ia dapat mengikuti gerakan Anda dengan menggerakkan kepalanya dari satu sisi hampir sampai pada sisi yang lain?',
                'kategori' => 'Gerak halus',
                'tipe_jawaban' => 'Ya/Tidak',
                'bobot_nilai' => 1,
                'petunjuk_gambar' => 'pertanyaan/petunjuk_gambar/1757393624_6.png',
                'created_at' => '2025-09-08 21:53:44',
                'updated_at' => '2025-09-08 21:53:44',
            ],
            [
                'id' => 8,
                'formulir_id' => 1,
                'nomor' => 8,
                'teks' => 'Pada saat bayi tengkurap di alas yang datar, apakah ia dapat mengangkat kepalanya seperti pada gambar?',
                'kategori' => 'Gerak kasar',
                'tipe_jawaban' => 'Ya/Tidak',
                'bobot_nilai' => 1,
                'petunjuk_gambar' => 'pertanyaan/petunjuk_gambar/1757393624_7.png',
                'created_at' => '2025-09-08 21:53:44',
                'updated_at' => '2025-09-08 21:53:44',
            ],
            [
                'id' => 9,
                'formulir_id' => 1,
                'nomor' => 9,
                'teks' => 'Pada saat bayi tengkurap di alas yang datar, apakah ia dapat mengangkat kepalanya sehingga membentuk sudut 45˚ seperti pada gambar?',
                'kategori' => 'Gerak kasar',
                'tipe_jawaban' => 'Ya/Tidak',
                'bobot_nilai' => 1,
                'petunjuk_gambar' => 'pertanyaan/petunjuk_gambar/1757393624_8.png',
                'created_at' => '2025-09-08 21:53:44',
                'updated_at' => '2025-09-08 21:53:44',
            ],
            [
                'id' => 10,
                'formulir_id' => 1,
                'nomor' => 10,
                'teks' => 'Pada saat bayi tengkurap di alas yang datar, apakah ia dapat mengangkat kepalanya dengan tegak seperti pada gambar?',
                'kategori' => 'Gerak kasar',
                'tipe_jawaban' => 'Ya/Tidak',
                'bobot_nilai' => 1,
                'petunjuk_gambar' => 'pertanyaan/petunjuk_gambar/1757393624_9.png',
                'created_at' => '2025-09-08 21:53:44',
                'updated_at' => '2025-09-08 21:53:44',
            ],
            [
                'id' => 11,
                'formulir_id' => 2,
                'nomor' => 1,
                'teks' => 'Bayi diposisikan terlentang. Ambil gulungan wool merah, letakkan di atas wajah di depan mata bayi. Gerakkan wool dari samping kiri ke kanan kepala. Apakah ia dapat mengikuti gerakan Anda dengan menggerakkan kepala sepenuhnya dari satu ke sisi yang lain?',
                'kategori' => 'Gerak halus',
                'tipe_jawaban' => 'Ya/Tidak',
                'bobot_nilai' => 1,
                'petunjuk_gambar' => 'pertanyaan/petunjuk_gambar/1757402964_0.png',
                'created_at' => '2025-09-09 00:29:24',
                'updated_at' => '2025-09-09 00:29:24',
            ],
            [
                'id' => 12,
                'formulir_id' => 2,
                'nomor' => 2,
                'teks' => "Pada posisi bayi terlentang, pegang kedua\r\ntangannya lalu tarik perlahan ke posisi duduk.\r\nDapatkah bayi mempertahankan lehernya\r\nsecara kaku seperti pada gambar? Jawab\r\n‘Tidak’ bila kepala bayi jatuh kembali seperti\r\ngambar.",
                'kategori' => 'Gerak kasar',
                'tipe_jawaban' => 'Ya/Tidak',
                'bobot_nilai' => 1,
                'petunjuk_gambar' => 'pertanyaan/petunjuk_gambar/1757402964_1.png',
                'created_at' => '2025-09-09 00:29:24',
                'updated_at' => '2025-09-09 00:29:24',
            ],
            [
                'id' => 13,
                'formulir_id' => 2,
                'nomor' => 3,
                'teks' => "Ketika bayi tengkurap di alas yang datar, apakah ia dapat\r\nmengangkat dada dengan kedua lengannya sebagai\r\npenyangga seperti pada gambar?",
                'kategori' => 'Gerak kasar',
                'tipe_jawaban' => 'Ya/Tidak',
                'bobot_nilai' => 1,
                'petunjuk_gambar' => 'pertanyaan/petunjuk_gambar/1757402964_2.png',
                'created_at' => '2025-09-09 00:29:24',
                'updated_at' => '2025-09-09 00:29:24',
            ],
            [
                'id' => 14,
                'formulir_id' => 2,
                'nomor' => 4,
                'teks' => "Bayi dipangku orang tua atau pengasuh. Dapatkah bayi mempertahankan\r\nposisi kepala dalam keadaan tegak dan stabil? Jawab ‘Tidak’ bila kepala bayi\r\ncenderung jatuh ke kanan, kiri, atau ke dadanya.",
                'kategori' => 'Gerak kasar',
                'tipe_jawaban' => 'Ya/Tidak',
                'bobot_nilai' => 1,
                'petunjuk_gambar' => null,
                'created_at' => '2025-09-09 00:29:24',
                'updated_at' => '2025-09-09 00:29:24',
            ],
            [
                'id' => 15,
                'formulir_id' => 2,
                'nomor' => 5,
                'teks' => "Bayi dipangku orang tua atau pengasuh. Sentuhkan pensil di punggung tangan\r\natau ujung jari bayi (jangan meletakkan di atas telapak tangan bayi). Apakah\r\nbayi dapat menggenggam pensil itu selama beberapa detik?",
                'kategori' => 'Gerak halus',
                'tipe_jawaban' => 'Ya/Tidak',
                'bobot_nilai' => 1,
                'petunjuk_gambar' => 'pertanyaan/petunjuk_gambar/1757402964_4.png',
                'created_at' => '2025-09-09 00:29:24',
                'updated_at' => '2025-09-09 00:29:24',
            ],
            [
                'id' => 16,
                'formulir_id' => 2,
                'nomor' => 6,
                'teks' => "Bayi dipangku orang tua atau pengasuh. Dapatkah bayi mengarahkan\r\nmatanya pada benda kecil sebesar kacang, kismis atau uang logam? Jawab\r\n‘Tidak’ jika ia tidak dapat mengarahkan matanya",
                'kategori' => 'Gerak halus',
                'tipe_jawaban' => 'Ya/Tidak',
                'bobot_nilai' => 1,
                'petunjuk_gambar' => null,
                'created_at' => '2025-09-09 00:29:24',
                'updated_at' => '2025-09-09 00:29:24',
            ],
            [
                'id' => 17,
                'formulir_id' => 2,
                'nomor' => 7,
                'teks' => "Bayi dipangku orang tua atau pengasuh. Dapatkah bayi meraih mainan yang\r\ndiletakkan agak jauh namun masih berada dalam jangkauan tangannya?",
                'kategori' => 'Gerak halus',
                'tipe_jawaban' => 'Ya/Tidak',
                'bobot_nilai' => 1,
                'petunjuk_gambar' => null,
                'created_at' => '2025-09-09 00:29:24',
                'updated_at' => '2025-09-09 00:29:24',
            ],
            [
                'id' => 18,
                'formulir_id' => 2,
                'nomor' => 8,
                'teks' => "Tanyakan kepada orang tua atau pengasuh, pernahkah bayi berbalik paling\r\nsedikit 2 kali, dari terlentang ke tengkurap atau sebaliknya?",
                'kategori' => 'Gerak kasar',
                'tipe_jawaban' => 'Ya/Tidak',
                'bobot_nilai' => 1,
                'petunjuk_gambar' => null,
                'created_at' => '2025-09-09 00:29:24',
                'updated_at' => '2025-09-09 00:29:24',
            ],
            [
                'id' => 19,
                'formulir_id' => 2,
                'nomor' => 9,
                'teks' => "Tanyakan kepada orang tua atau pengasuh, pernahkah bayi mengeluarkan\r\nsuara gembira bernada tinggi ataumemekik tetapi bukan menangis?",
                'kategori' => 'Bicara dan bahasa',
                'tipe_jawaban' => 'Ya/Tidak',
                'bobot_nilai' => 1,
                'petunjuk_gambar' => null,
                'created_at' => '2025-09-09 00:29:24',
                'updated_at' => '2025-09-09 00:29:24',
            ],
            [
                'id' => 20,
                'formulir_id' => 2,
                'nomor' => 10,
                'teks' => "Tanyakan kepada orang tua atau pengasuh, pernahkah orang tua atau\r\npengasuh melihat bayi tersenyum ketika melihat mainan yang lucu, gambar,\r\natau binatang peliharaan pada saat ia bermain sendiri?",
                'kategori' => 'Sosialisasi dan kemandirian',
                'tipe_jawaban' => 'Ya/Tidak',
                'bobot_nilai' => 1,
                'petunjuk_gambar' => null,
                'created_at' => '2025-09-09 00:29:24',
                'updated_at' => '2025-09-09 00:29:24',
            ],
        ]);
    }
}
